spring:
  application.name: "code-challenge"
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "consumer-group"
      auto-offset-reset: earliest
    bootstrap-servers: "localhost:9092"

player:
  current: "Player 2"
  opponent: "Player 1"

kafka:
  topic:
    winner:
      current: "win2-topic"
      opponent: "win1-topic"
    listener: "player2-topic"
    producer: "player1-topic"

server:
  port: 8082

logging:
  level:
    ROOT: ERROR
